version: '3.8'

services:
  numerist:
    build: .
    container_name: numerist
    restart: unless-stopped
    expose:
      - 3333
    environment:
      - NODE_ENV=production
      - PORT=3333
      - HOST=0.0.0.0

  nginx:
    image: nginx:alpine
    container_name: numerist_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - numerist 